services:
  client:
    restart: unless-stopped
    image: ghcr.io/oskarilindroos/airhockeygame/client
    ports:
      - "3000:3000"

  server:
    restart: unless-stopped
    image: ghcr.io/oskarilindroos/airhockeygame/server
    ports:
      - "5000:5000"

  proxy-manager:
    restart: unless-stopped
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    networks:
      - app-network
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  app-network:
    driver: bridge
