services:
  client:
    restart: unless-stopped
    image: ghcr.io/oskarilindroos/airhockeygame/client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  server:
    restart: unless-stopped
    image: ghcr.io/oskarilindroos/airhockeygame/server
    ports:
      - "5000:5000"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal -d airhockey.live --agree-tos
