services:
  client:
    restart: always
    image: ghcr.io/oskarilindroos/airhockeygame/client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf

  server:
    restart: always
    image: ghcr.io/oskarilindroos/airhockeygame/server
    ports:
      - "5000:5000"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1000; done'"
