services:
  client:
    restart: always
    image: ghcr.io/oskarilindroos/airhockeygame/client
    ports:
      - "80:80"
  server:
    restart: always
    image: ghcr.io/oskarilindroos/airhockeygame/server
    ports:
      - "5000:5000"
